# Site settings
title: UPC Linux
email: upclinux@163.com
footnote: > # this means to ignore newlines until "baseurl:"
  &copy; 2015 中国石油大学 (华东) Linux 协会<br>自豪地采用 GitHub Pages 和 Jekyll
baseurl: "/intro" # the subpath of your site, e.g. /blog/
url: "https://upclinux.github.io" # the base hostname & protocol for your site
permalink: /:short_year/:title
# twitter_username: jekyllrb
github_username:  upclinux
qqqun_name: "QQ 群 (279310694)"
qqqun_idkey: e47c6b546d3373c09f7eaa8d4173728a513975ed2d0ec20106e83cfb11a3bf08

host: 0.0.0.0 

# Build settings
markdown: kramdown

defaults:
- 
    scope:
        path: ""
        type: "posts"
    values:
        layout: "page"
        comments: "true"
- 
    scope:
        path: "novice"
    values:
        category: "我是新手"
- 
    scope:
        path: "c"
    values:
        category: "just for C 语言"
- 
    scope:
        path: "try"
    values:
        category: "准备接触 Linux"
- 
    scope:
        path: "configuration"
    values:
        category: "配置系统"
- 
    scope:
        path: "work"
    values:
        category: "工作与学习"
- 
    scope:
        path: "development"
    values:
        category: "开发者"
- 
    scope:
        path: "toy"
    values:
        category: "Linux 玩具"
- 
    scope:
        path: "future"
    values:
        category: "深入学习"
- 
    scope:
        path: "mac"
    values:
        category: "苹果"